services:
  discord-yt-bot:
    image: ghcr.io/dongcodebmt/discord-yt-bot:latest
    container_name: discord-yt-bot
    user: 1000:1000
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.env:/app/.env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: on-failure
